openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: "example-user-id-1"
                  username: "user-1"
                  name: "User"
                  surname: "Userenko"
                - id: "example-user-id-2"
                  username: "user-2"
                  name: "Testuser"
                  surname: "Testov"
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        name:
          type: string
        surname:
          type: string
